spring.application.name=estimavoto
spring.datasource.url=jdbc:postgresql://${DB_HOST}/estimavoto_api
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.HSQLDialect

spring.flyway.enabled=true

api.security.token.secret=${JWT_SECRET:123456}